const sceneNames = {
  CREATE_NEW_ORDER: 'CREATE_NEW_ORDER',
  START: 'START'
}

const actionNames = {
  CANCEL_ORDER: 'CANCEL_ORDER',
  DELIVERY_DECLINE_ORDER: 'DELIVERY_DECLINE_ORDER',
  DELIVERY_ACCEPT_ORDER: 'DELIVERY_ACCEPT_ORDER',
  SHOP_DECLINE_ORDER: 'SHOP_DECLINE_ORDER',
  SHOP_ACCEPT_ORDER: 'SHOP_ACCEPT_ORDER',
  BACK_TO_HOME: 'BACK_TO_HOME',
}

module.exports = {
  sceneNames,
  actionNames
}