[build]
  command = "vite build"
  functions = "functions"
  publish = "dist"
[dev]
  targetPort = 5173
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
